export const FETCH_FILES_REQUEST = "FETCH_FILES_REQUEST";
export const FETCH_USED_SPACE = "FETCH_USED_SPACE";
export const SET_SEARCH_QUERY = "SET_SEARCH_QUERY";
export const SET_TAB_BAR_VISIBLE = "SET_TAB_BAR_VISIBLE";
export const SET_FIRST_RENDER = "SET_FIRST_RENDER";
export const FETCH_LIKED_FILES = "FETCH_LIKED_FILES"
export const FETCH_FOLDERS = "FETCH_FOLDERS"
export const SET_ALL_FILES_METADATA = "SET_ALL_FILES_METADATA"
export const SET_ACTIVITY_LOGS = "SET_ACTIVITY_LOGS"

export const SET_RECYCLE_BIN_FILES = "SET_RECYCLE_BIN_FILES"

export const SET_USER = "SET_USER";

export const SET_PASSWORD = "SET_PASSWORD";

export const UPDATE_FILE_LIKE_STATUS = "UPDATE_FILE_LIKE_STATUS"

export const SET_AUTH_STATE = "SET_AUTH_STATE"

export const SET_STORAGE_INFO = "SET_STORAGE_INFO"