name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted  

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy to EC2 via SSH
        run: |
          cd ~/BioKey
          git pull origin main
          npm install
          pm2 restart all  # Restart the application using PM2